Repository futurewei-cloud/merak, pull requests merged in 2023-01, with the labels that each got.

#182 Topo: add hostname attribute for each pod
  api/proto/v1/common.proto
  services/merak-topo/database/entities.go
  services/merak-topo/handler/handler.go
Labels: enhancement

#185 Update README deployment section to reflect overlay changes
  README.md
Labels: documentation

#178 Merak-Topo: give namespace for each topo, rewrite log and error handling
  services/merak-topo/database/database.go
  services/merak-topo/database/entities.go
  services/merak-topo/grpc/service/service.go
  services/merak-topo/handler/handler.go
  services/merak-topo/handler/topo_deploy.go
  services/merak-topo/handler/topo_gen.go
  services/merak-topo/main.go
  services/merak-topo/tests/handler_create_test.go
  services/merak-topo/tests/handler_delete_test.go
  services/merak-topo/tests/handler_info_test.go
  services/merak-topo/tests/handler_test.go
  services/merak-topo/utils/utils.go
Labels: enhancement

#184 Scenario: allowing different size of VPC to be deployed in the compute
  services/scenario-manager/handler/deploy.go
  services/scenario-manager/handler/message.go
Labels: enhancement

#187 Merak-topo Unit Test
  services/merak-topo/database/compute_entity_test.go
  services/merak-topo/database/host_entity_test.go
  services/merak-topo/tests/db_test.go
  services/merak-topo/tests/handler_create_test.go
  services/merak-topo/tests/handler_delete_test.go
  services/merak-topo/tests/handler_info_test.go
  services/merak-topo/tests/handler_test.go
  services/merak-topo/tests/main_test.go
Labels: test

#192 Deployment: Update k8s alcor docker image tag in the kustomization.yaml
  deployments/kubernetes/alcor/kustomization.yaml
Labels: deployment

#193 Topo: Evenly distribute pods on k8s worker nodes
  services/merak-topo/handler/topo_deploy.go
Labels: enhancement
